language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-head
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  exclude:
    - rvm: jruby-19mode
      env:
    - rvm: jruby-head
      env:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
