language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - jruby-19mode
  - jruby-1.7.23
  - jruby-9.0.4.0
  - jruby-head
  - rbx-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: jruby-head
before_install:
  - gem update bundler
